[package]
name = "bevy_retro"
version = "0.1.0"
authors = ["Zicklag <zicklag@katharostech.com>"]
edition = "2018"

[workspace]
members = [
    ".",
    "plugins/bevy_retro_ldtk"
]

[features]
default = [
    "jpeg",
    "png",
]
gif = ["image/gif"]
jpeg = ["image/jpeg"]
png = ["image/png"]
tga = ["image/tga"]
tiff = ["image/tiff"]
webp = ["image/webp"]
bmp = ["image/bmp"]

[dependencies]
glow = "0.8.1"
image = { version = "0.23.14", default-features = false }
thiserror = "1.0.24"
anyhow = "1.0.38"
fixedbitset = "0.3.2"
petgraph = "0.5.1"
rand = "0.8.3"
getrandom = { version = "0.2.2", features = ["js"] }

[dependencies.bevy]
git = "https://github.com/bevyengine/bevy"
default-features = false
features = ["bevy_winit", "x11"]

[target.'cfg(not(any(target_arch = "wasm32")))'.dependencies]
glutin = { version = "0.26" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
winit = { version = "0.24", features = ["web-sys"] }
web-sys = { version = "0.3", features=["HtmlCanvasElement", "WebGl2RenderingContext", "Window", "console"] }
wasm-bindgen = { version = "0.2" }

[build-dependencies]
cfg_aliases = "0.1.1"

[profile.dev]
opt-level = 3
debug = 1

[profile.release]
lto = true
