[package]
name = "bevy_retro"
version = "0.0.0"
authors = ["Zicklag <zicklag@katharostech.com>"]
edition = "2018"

documentation = "https://docs.rs/bevy_retro"
repository = "https://github.com/katharostech/bevy_retro"
readme = "README.md"
license-file = "LICENSE.md"

keywords = ["bevy", "2D", "pixel-perfect", "retro", "renderer", "web"]
categories = ["game-development", "multimedia", "rendering::engine"]

[workspace]
members = [
    ".",
    "plugins/bevy_retro_ldtk"
]

[features]
default = [
    "jpeg",
    "png",
]
gif = ["image/gif"]
jpeg = ["image/jpeg"]
png = ["image/png"]
tga = ["image/tga"]
tiff = ["image/tiff"]
webp = ["image/webp"]
bmp = ["image/bmp"]

[dependencies]
luminance-front = "0.3.1"
luminance-windowing = "0.9.3"
luminance = { version = "0.43.2", features = ["derive"] }

winit = { version = "0.24", features = ["web-sys"] }
image = { version = "0.23.14", default-features = false }
thiserror = "1.0.24"
anyhow = "1.0.38"
fixedbitset = "0.3.2"
petgraph = "0.5.1"
rand = "0.8.3"
getrandom = { version = "0.2.2", features = ["js"] }
parking_lot = { version = "0.11.1" }
tracing = "0.1.25"

[dependencies.bevy]
git = "https://github.com/bevyengine/bevy"
default-features = false
features = ["bevy_winit", "x11"]

[target.'cfg(not(any(target_arch = "wasm32")))'.dependencies]
luminance-surfman = { path = "../luminance-surfman" }
luminance-gl = "0.16.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
# Waiting on PR: https://github.com/phaazon/luminance-rs/pull/489. For now we have a copy locally.
# luminance-web-sys = "0.2.2"
luminance-webgl = "0.3.2"
web-sys = { version = "0.3", features=["HtmlCanvasElement", "WebGl2RenderingContext", "Window", "console"] }
wasm-bindgen = { version = "0.2" }

[build-dependencies]
cfg_aliases = "0.1.1"

[profile.dev]
opt-level = 3
debug = 1

[profile.release]
lto = true
