[package]
name = "bevy_retro"
version = "0.1.0"
authors = ["Zicklag <zicklag@katharostech.com>"]
edition = "2018"

[features]
default = [
    "jpeg",
    "png",
]
gif = ["image/gif"]
jpeg = ["image/jpeg"]
png = ["image/png"]
tga = ["image/tga"]
tiff = ["image/tiff"]
webp = ["image/webp"]
bmp = ["image/bmp"]

[dependencies]
glow = "0.8.1"
image = { version = "0.23.14", default-features = false }
thiserror = "1.0.24"
anyhow = "1.0.38"

[dependencies.bevy]
git = "https://github.com/bevyengine/bevy"
rev = "b17f8a4bce5551b418654fffb1fe97ff0f9852f0"
default-features = false
features = ["bevy_winit", "x11"]

[target.'cfg(not(any(target_arch = "wasm32")))'.dependencies]
glutin = { version = "0.26" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
winit = { version = "0.24", features = ["web-sys"] }
web-sys = { version = "0.3", features=["HtmlCanvasElement", "WebGl2RenderingContext", "Window", "console"] }
wasm-bindgen = { version = "0.2" }

[build-dependencies]
cfg_aliases = "0.1.1"
